### ISSUE TITLE
Add SDL2 library

### ISSUE THREAD

**Issue by pazos** [koreader/koreader-base#1141]
To use on mac. There's no need to use it on other sdl targets unless we want the appname as "KOReader" instead of luajit. But on mac (the app, not the emulator) we might want to fine tweak some cocoa things.

To build the dyamic library I did:

```
git clone https://github.com/spurious/SDL-mirror.git
cd SDL-mirror
mkdir mac_build
cd mac_build
cmake -DCMAKE_BUILD_TYPE=Release -DSDL_TEST=OFF -DSDL_SHARED=ON -DSDL_STATIC=OFF ..
cmake -build .
```

**Comment by pazos** [comment]
@Frenzie @NiLuJe : any hint on turning that into a thirdparty library?. I'm still a bit lost with CMake hell (or build systems in general) :smiley:

**Comment by JasonInOttawa** [comment]
Cool. Does this

DSDL_SHARED=ON -DSDL_STATIC=OFF

Remove the need to use install_name_tool to fix path names in the dylib file?

**Comment by Frenzie** [comment]
@pazos There are two ways. There's the one I successfully implemented for sdcv (see [here](https://github.com/koreader/koreader-base/blob/7f16d22047a0df9616f89051de73ece76ea5e62a/thirdparty/sdcv/CMakeLists.txt)), which avoids generating a separate CMake project. This makes it easier to set variables in normal CMake style and it saves some time by not reconfiguring.

The other way is how sdcv used to be, and how pretty much all the other dependencies are.

It's probably better to copy current sdcv because that way we stay within CMake logic.
