### ISSUE TITLE
Why "platform=android-9" is fixed used when building on android?

### ISSUE THREAD

**Issue by snailfu** [koreader/koreader-base#332]
I think platform=android-x is an open selection when building on different android targets (2.3, 4.0, 4.1, 4.4 or 5.x). But I found in nearly all android related build scripts the "platform=android-9" is hard-coded. May I ask why should it be done like this rather than providing it for user determination? Thanks

**Comment by hwhw** [comment]
Because we build the project-provided APKs that way. It determines the API compatibility and we want to target as many devices as we can. Since there's backward compatibility anyway, it shouldn't matter. We just can't go before android-9 since some of our stuff uses APIs that only got introduced at that point. And there's not much point in enforcing a newer API, is there?

**Comment by Frenzie** [comment]
I would assume you generally want to build for the lowest version possible as the default.

**Comment by snailfu** [comment]
Thanks first.
I asked it because I found the building depending on the NDK version.
Below snapshot is when I build with "make TARGET=android androidupdate", it fails at the step of building base/libk2pdfopt/leptonica-1.69/liblept.so
![2015-07-27 22 58 41](https://cloud.githubusercontent.com/assets/2015504/8909337/6b849060-34b3-11e5-998a-4c57de415b64.png)
When I make the output noisy, I get below:
![2015-07-27 23 22 57](https://cloud.githubusercontent.com/assets/2015504/8909943/a932206e-34b6-11e5-95f8-a4f1d838378b.png)
So, it seems the function "rand" can't be found at link time.
This is because in the ${ndk-sysroot}/platforms/android-9/arch-arm/usr/lib/libc.so of android-9 platform, there is no rand function.
But I can find it in the ${ndk-sysroot}/platforms/android-21/arch-arm/usr/lib/libc.so, so after I build with all with platform=android-21, it success.
My question is how the inconsistent is made? And how can I solve it gracefully? Is it made by the NDK version of "android-ndk-r10e" is used which is too update-to-date? Or simply change the platform=android-9 to android-21 is acceptable? Thanks

**Comment by hwhw** [comment]
I guess you're right with the guess that it is about the NDK version. We probably used older NDKs which had "rand" onboard.

But then it really makes me wonder because "rand" should be there. And it seems to be an error in the compilation stage, not the linking stage. I guess it's the header files.

However, it should probably not compile the binaries in the /prog subfolder at all. I can't quite make sense of it right now.

**Comment by snailfu** [comment]
Thanks hwhw, you are right, in android-9 sysroot, the "rand" in header file as inline function, so there is no specific "rand" symbol in libc.so. 
For the compiled .o file must not been cleared totally, so the compiled .o file which compiled to android-21 platform header tries to link "rand" symbol to android-9 platform library, so the error happened. After I cleared all .o again, the problem disappears.

**Comment by Frenzie** [comment]
Closing this now.
